version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cvsu-arm-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cvsu_arm_db
      MYSQL_USER: cvsu_arm_user
      MYSQL_PASSWORD: cvsu_arm_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
